In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
def read_train_test_class_dist(file_name):
    train_class_dist = {}
    file = open(file_name)
    file.readline()
    line = file.readline()
    while line.startswith('CLASS'):
        dat = line.split(' ')
        train_class_dist[dat[1]] = dat[4]

        line=file.readline()

    test_class_dist = {}
    while line.startswith('CLASS'):
        dat = line.split(' ')
        test_class_dist[dat[1]] = dat[4]

        line=file.readline()
    
    return train_class_dist,test_class_dist

def read_true_predicted_counts(file_name):
    train_class_dist = {}
    file = open(file_name)
    file.readline()
    line = file.readline()
    while line.startswith('Class'):
        dat = line.split(' ')
        train_class_dist[dat[1]] = dat[5][:-1]

        line=file.readline()

    test_class_dist = {}
    line = file.readline()
    while line.startswith('Class'):
        dat = line.split(' ')
        test_class_dist[dat[1]] = dat[5][:-1]

        line=file.readline()
    
    return train_class_dist,test_class_dist

In [35]:
training_metrics = pd.read_csv('/home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/divergence_pipeline/outputs/pyrome_26_equal_3M/LR_training_accuracy_baseline.csv')
results_path = '/home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/divergence_pipeline/outputs/pyrome_26_equal_3M/tile_fbfm40_accuracy_metrics_pyrome_26.csv'
results_df = pd.read_csv(results_path)
old_results_df = pd.read_csv('/home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/divergence_pipeline/outputs/tile_fbfm40_accuracy_metrics_pyrome_26.csv')

train_class_dist, test_class_dist = read_train_test_class_dist('/home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/divergence_pipeline/test_dist_3M.txt')

tile_306_true_dist, tile_306_pred_dist = read_true_predicted_counts('/home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/divergence_pipeline/pyrome_26_tile_306_dist.txt')
tile_437_true_dist, tile_437_pred_dist = read_true_predicted_counts('/home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/divergence_pipeline/pyrome_26_tile_437_dist.txt')
tile_439_true_dist, tile_439_pred_dist = read_true_predicted_counts('/home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/divergence_pipeline/pyrome_26_tile_439_dist.txt')

In [ ]:
training_metrics[['model_accuracy','model_f1_weighted']]

   model_accuracy  model_f1_weighted
0        0.730271           0.726872

In [37]:
results_df[['tile','accuracy','f1_weighted']]

   tile  accuracy  f1_weighted
0   305  0.205162     0.133296
1   306  0.292200     0.276952
2   371  0.163060     0.135840
3   437  0.122240     0.082237
4   439  0.422666     0.422656

In [36]:
old_results_df[['tile','accuracy','f1_weighted']]

    tile  accuracy  f1_weighted
0    303  0.050508     0.015104
1    304  0.040529     0.006716
2    305  0.016946     0.003366
3    306  0.033647     0.019800
4    366  0.062580     0.013756
5    367  0.063373     0.012022
6    368  0.045595     0.019716
7    369  0.053735     0.035710
8    370  0.088944     0.123954
9    371  0.225509     0.286713
10   372  0.156630     0.190774
11   373  0.208859     0.218199
12   432  0.147478     0.122474
13   433  0.154902     0.143643
14   434  0.229472     0.166268
15   435  0.202715     0.155635
16   436  0.319211     0.204524
17   437  0.394171     0.386150
18   438  0.183181     0.233682
19   439  0.289646     0.302101
20   499  0.043547     0.015819
21   500  0.056491     0.037954
22   501  0.048507     0.040713
23   502  0.098171     0.098930
24   503  0.047807     0.077990
25   504  0.012375     0.020989